#!/bin/bash

mkdir -p build

mkdir -p build/VertexShader
mkdir -p build/FragShader

glslc src/VertexShader/triangle.vert -o build/VertexShader/vert.spv
glslc src/FragShader/triangle.frag -o build/FragShader/frag.spv

cd build
cmake -S ../
make
